In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
from lxml import etree
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
import selenium.webdriver.support.expected_conditions as EC
from tqdm.notebook import tqdm
import time
import psycopg2
import json
import re

In [4]:
class postgres_conn:
    def getConn(self):
        try:
            connection = psycopg2.connect(user='postgres',
                                          password='postgres_007',
                                          host="1.pgsql.db.1digitalstack.com",
                                          port='5432',
                                          database='postgres')

            cursor = connection.cursor()
            # Print PostgreSQL Connection properties
            print(connection.get_dsn_parameters(), "\n")

            # Print PostgreSQL version
            return cursor, connection

        except (Exception, psycopg2.Error) as error:
            print("Error while connecting to PostgreSQL", error)
            return error, error
    def getConn2(self):
        try:
            connection = psycopg2.connect(user='postgres',
                                          password='reporting_007',
                                          host="2.pgsql.db.1digitalstack.com",
                                          port='5432',
                                          database='postgres')

            cursor = connection.cursor()
            # Print PostgreSQL Connection properties
            print(connection.get_dsn_parameters(), "\n")

            # Print PostgreSQL version
            return cursor, connection

        except (Exception, psycopg2.Error) as error:
            print("Error while connecting to PostgreSQL", error)
            return error, error


    def close_connection(self, cursor, connection):
        # closing database connection.
        if(connection):
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")
            
pg = postgres_conn()
conn = pg.getConn()
conn2 = pg.getConn2()

{'user': 'postgres', 'channel_binding': 'prefer', 'dbname': 'postgres', 'host': '1.pgsql.db.1digitalstack.com', 'port': '5432', 'options': '', 'sslmode': 'prefer', 'sslcompression': '0', 'sslsni': '1', 'ssl_min_protocol_version': 'TLSv1.2', 'gssencmode': 'disable', 'krbsrvname': 'postgres', 'target_session_attrs': 'any'}

{'user': 'postgres', 'channel_binding': 'prefer', 'dbname': 'postgres', 'host': '2.pgsql.db.1digitalstack.com', 'port': '5432', 'options': '', 'sslmode': 'prefer', 'sslcompression': '0', 'sslsni': '1', 'ssl_min_protocol_version': 'TLSv1.2', 'gssencmode': 'disable', 'krbsrvname': 'postgres', 'target_session_attrs': 'any'}

In [5]:
job_id=input("Enter keystone ids with comma.").split(",")
days=input(" Enter no of days for which data needs brand mapping.\n")
job_id.append("")
tuple(job_id)

#64ad5178b732b6c8d30ed4fa,64a7aef292a955755975d804,64a7ab5792a955755975d6a0

Enter keystone ids with comma.64d1d1b359aa371d9ed1a214
 Enter no of days for which data needs brand mapping.
2

('64d1d1b359aa371d9ed1a214', '')

In [6]:
query = f"""
select brand,title,sku,job_name,channel_id
from ready.serp_details smd join ready.serp_mongo_details m on m.serp_mongo_id=smd.serp_mongo_id
where smd.crawl_date > now() - interval '{days} day' and keystone_job_id in {tuple(job_id)}
"""
serp_details = pd.read_sql_query(query, conn[1])

C:\Users\Administrator\AppData\Local\Temp\2\ipykernel_102920\2162843895.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  serp_details = pd.read_sql_query(query, conn[1])

In [7]:
serp_details

,brand,title,sku,job_name,channel_id
0,VITAMIX,Vitamix A2500 Ascent 10-Speed Blender,1070978195,Liverpool r.no.565 Serp_job,97
1,IUSA,IUSA electrical extension 5 meters,1136990396,Liverpool r.no.565 Serp_job,97
2,IUSA,IUSA electrical extension 5 meters,1136991236,Liverpool r.no.565 Serp_job,97
3,IUSA,IUSA electrical extension 2 meters,1136990400,Liverpool r.no.565 Serp_job,97
4,IUSA,IUSA electrical extension 5 meters,1136990418,Liverpool r.no.565 Serp_job,97
...,...,...,...,...,...
4625,NAVY PIER,Navy Pier Ultra Bullet Muller Personal Blender...,1128919887,Liverpool r.no.565 Serp_job,97
4626,NAVY PIER,Navy Pier Ultra Bullet Muller Personal Blender...,1126869483,Liverpool r.no.565 Serp_job,97
4627,MULTILASER,Multilaser Shake 2-speed blender BE013USA,1129353267,Liverpool r.no.565 Serp_job,97
4628,SMEG,Smeg PBF01PKUS 2-speed personal blender,1133280096,Liverpool r.no.565 Serp_job,97
4629,POWER XL,PowerXL Blender BL6018-0BPLA 3 speeds,1135344423,Liverpool r.no.565 Serp_job,97

In [8]:
df=serp_details.copy()
df

,brand,title,sku,job_name,channel_id
0,VITAMIX,Vitamix A2500 Ascent 10-Speed Blender,1070978195,Liverpool r.no.565 Serp_job,97
1,IUSA,IUSA electrical extension 5 meters,1136990396,Liverpool r.no.565 Serp_job,97
2,IUSA,IUSA electrical extension 5 meters,1136991236,Liverpool r.no.565 Serp_job,97
3,IUSA,IUSA electrical extension 2 meters,1136990400,Liverpool r.no.565 Serp_job,97
4,IUSA,IUSA electrical extension 5 meters,1136990418,Liverpool r.no.565 Serp_job,97
...,...,...,...,...,...
4625,NAVY PIER,Navy Pier Ultra Bullet Muller Personal Blender...,1128919887,Liverpool r.no.565 Serp_job,97
4626,NAVY PIER,Navy Pier Ultra Bullet Muller Personal Blender...,1126869483,Liverpool r.no.565 Serp_job,97
4627,MULTILASER,Multilaser Shake 2-speed blender BE013USA,1129353267,Liverpool r.no.565 Serp_job,97
4628,SMEG,Smeg PBF01PKUS 2-speed personal blender,1133280096,Liverpool r.no.565 Serp_job,97
4629,POWER XL,PowerXL Blender BL6018-0BPLA 3 speeds,1135344423,Liverpool r.no.565 Serp_job,97

In [13]:
df.drop_duplicates(subset='sku', inplace=True)
df

,brand,title,sku,job_name,channel_id,categories
0,OSTER,Oster 2-speed blender 2114087/BEST02-E00-13,1109553111,Liverpool r.no.565 Serp_job,97,
1,OSTER,Oster BLSTBPST-013 2-speed blender 2114099,1104553521,Liverpool r.no.565 Serp_job,97,
2,OSTER,Oster blender BLST4655-013 3 speeds 2114081,1104552770,Liverpool r.no.565 Serp_job,97,
3,OSTER,Oster Osterizer Cycle Blend Vintage 10-Speed B...,1109553081,Liverpool r.no.565 Serp_job,97,
4,OSTER,Oster 2114101 2 speed blender,1104756146,Liverpool r.no.565 Serp_job,97,
...,...,...,...,...,...,...
2071,AVENT,Set milk storage bags Avent SCF603/25,1044138782,Liverpool r.no.565 Serp_job,97,
2072,PHILIPS,Philips Series 5000 Shaver S5898/17,1135400528,Liverpool r.no.565 Serp_job,97,
2073,AVENT,Avent Formula Dispenser,1044138502,Liverpool r.no.565 Serp_job,97,
2074,AVENT,Avent Baby Bottles 9oz,1094071654,Liverpool r.no.565 Serp_job,97,
2090,OSTER,Oster reversible blade 6 blades,1115561690,Liverpool r.no.565 Serp_job,97,

In [14]:
df=df.reset_index()
df

,index,brand,title,sku,job_name,channel_id,categories
0,0,OSTER,Oster 2-speed blender 2114087/BEST02-E00-13,1109553111,Liverpool r.no.565 Serp_job,97,
1,1,OSTER,Oster BLSTBPST-013 2-speed blender 2114099,1104553521,Liverpool r.no.565 Serp_job,97,
2,2,OSTER,Oster blender BLST4655-013 3 speeds 2114081,1104552770,Liverpool r.no.565 Serp_job,97,
3,3,OSTER,Oster Osterizer Cycle Blend Vintage 10-Speed B...,1109553081,Liverpool r.no.565 Serp_job,97,
4,4,OSTER,Oster 2114101 2 speed blender,1104756146,Liverpool r.no.565 Serp_job,97,
...,...,...,...,...,...,...,...
731,2071,AVENT,Set milk storage bags Avent SCF603/25,1044138782,Liverpool r.no.565 Serp_job,97,
732,2072,PHILIPS,Philips Series 5000 Shaver S5898/17,1135400528,Liverpool r.no.565 Serp_job,97,
733,2073,AVENT,Avent Formula Dispenser,1044138502,Liverpool r.no.565 Serp_job,97,
734,2074,AVENT,Avent Baby Bottles 9oz,1094071654,Liverpool r.no.565 Serp_job,97,
735,2090,OSTER,Oster reversible blade 6 blades,1115561690,Liverpool r.no.565 Serp_job,97,

In [61]:

df['categories']=''
df['sold_by']=''
df['rating_count']=''
df

,index,brand,title,sku,job_name,channel_id,categories,sold_by,rating_count
0,0,OSTER,Oster 2-speed blender 2114087/BEST02-E00-13,1109553111,Liverpool r.no.565 Serp_job,97,,,
1,1,OSTER,Oster BLSTBPST-013 2-speed blender 2114099,1104553521,Liverpool r.no.565 Serp_job,97,,,
2,2,OSTER,Oster blender BLST4655-013 3 speeds 2114081,1104552770,Liverpool r.no.565 Serp_job,97,,,
3,3,OSTER,Oster Osterizer Cycle Blend Vintage 10-Speed B...,1109553081,Liverpool r.no.565 Serp_job,97,,,
4,4,OSTER,Oster 2114101 2 speed blender,1104756146,Liverpool r.no.565 Serp_job,97,,,
...,...,...,...,...,...,...,...,...,...
731,2071,AVENT,Set milk storage bags Avent SCF603/25,1044138782,Liverpool r.no.565 Serp_job,97,,,
732,2072,PHILIPS,Philips Series 5000 Shaver S5898/17,1135400528,Liverpool r.no.565 Serp_job,97,,,
733,2073,AVENT,Avent Formula Dispenser,1044138502,Liverpool r.no.565 Serp_job,97,,,
734,2074,AVENT,Avent Baby Bottles 9oz,1094071654,Liverpool r.no.565 Serp_job,97,,,
735,2090,OSTER,Oster reversible blade 6 blades,1115561690,Liverpool r.no.565 Serp_job,97,,,

In [51]:
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--incognito")
driver = webdriver.Chrome(executable_path = r'chromedriver.exe',chrome_options = chrome_options)

C:\Users\kpind\AppData\Local\Temp/ipykernel_8876/1496906039.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path = r'chromedriver.exe',chrome_options = chrome_options)
C:\Users\kpind\AppData\Local\Temp/ipykernel_8876/1496906039.py:3: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path = r'chromedriver.exe',chrome_options = chrome_options)

In [99]:
for i in tqdm(range(0,5)):
    Url='https://www.liverpool.com.mx/tienda/pdp/-/'+df['sku'][i]+'?skuid='+df['sku'][i]
#     chrome_options = webdriver.ChromeOptions()
#     chrome_options.add_argument("--incognito")
#     driver = webdriver.Chrome(executable_path = r'chromedriver.exe',chrome_options = chrome_options)

    print('************************')
    print(i)
    print(Url)

    driver.get(Url)
    time.sleep(2)
    bs=BeautifulSoup(driver.page_source, "html.parser")
    
    try:
        aa=bs.find('li',class_="active")
        
        cat=[aa.text.strip()]
        print("category:",cat)
           
        df['categories'][i]=cat
        
    except:
        
        df['categories'][i]=""
        
        
    try:
        seller=bs.find('a', class_="a-productInfo__selledByLink").text
        print("sold by:" ,seller)
        df['sold_by'][i]=seller
    except:
        df['sold_by'][i]=""
        
    try:
        rating=bs.find('div',class_="RRBox").text
        print("rating_count:" ,rating)
        df['rating_count'][i]=rating
    except:
        df['rating_count'][i]=""

  0%|          | 0/5 [00:00<?, ?it/s]

************************
0
https://www.liverpool.com.mx/tienda/pdp/-/1109553111?skuid=1109553111
category: ['Licuadoras']
sold by: STOREPOOL
************************
1
https://www.liverpool.com.mx/tienda/pdp/-/1104553521?skuid=1104553521

C:\Users\kpind\AppData\Local\Temp/ipykernel_8876/2842102046.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['categories'][i]=cat
C:\Users\kpind\AppData\Local\Temp/ipykernel_8876/2842102046.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sold_by'][i]=seller
C:\Users\kpind\AppData\Local\Temp/ipykernel_8876/2842102046.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating_count'][i]=""

category: ['Licuadoras']
************************
2
https://www.liverpool.com.mx/tienda/pdp/-/1104552770?skuid=1104552770

C:\Users\kpind\AppData\Local\Temp/ipykernel_8876/2842102046.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sold_by'][i]=""

category: ['Licuadoras']
rating_count:   77 opiniones Escribe una opiniÃ³n
************************
3
https://www.liverpool.com.mx/tienda/pdp/-/1109553081?skuid=1109553081

C:\Users\kpind\AppData\Local\Temp/ipykernel_8876/2842102046.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating_count'][i]=rating

category: ['Licuadoras']
sold by: IBUSHAK
rating_count:  1 opiniÃ³n Escribe una opiniÃ³n
************************
4
https://www.liverpool.com.mx/tienda/pdp/-/1104756146?skuid=1104756146
category: ['Licuadoras']
rating_count:   37 opiniones Escribe una opiniÃ³n

In [100]:
df

,index,brand,title,sku,job_name,channel_id,categories,sold_by,rating_count
0,0,OSTER,Oster 2-speed blender 2114087/BEST02-E00-13,1109553111,Liverpool r.no.565 Serp_job,97,[Licuadoras],STOREPOOL,
1,1,OSTER,Oster BLSTBPST-013 2-speed blender 2114099,1104553521,Liverpool r.no.565 Serp_job,97,[Licuadoras],,
2,2,OSTER,Oster blender BLST4655-013 3 speeds 2114081,1104552770,Liverpool r.no.565 Serp_job,97,[Licuadoras],,77 opiniones Escribe una opiniÃ³n
3,3,OSTER,Oster Osterizer Cycle Blend Vintage 10-Speed B...,1109553081,Liverpool r.no.565 Serp_job,97,[Licuadoras],IBUSHAK,1 opiniÃ³n Escribe una opiniÃ³n
4,4,OSTER,Oster 2114101 2 speed blender,1104756146,Liverpool r.no.565 Serp_job,97,[Licuadoras],,37 opiniones Escribe una opiniÃ³n
...,...,...,...,...,...,...,...,...,...
731,2071,AVENT,Set milk storage bags Avent SCF603/25,1044138782,Liverpool r.no.565 Serp_job,97,,,
732,2072,PHILIPS,Philips Series 5000 Shaver S5898/17,1135400528,Liverpool r.no.565 Serp_job,97,,,
733,2073,AVENT,Avent Formula Dispenser,1044138502,Liverpool r.no.565 Serp_job,97,,,
734,2074,AVENT,Avent Baby Bottles 9oz,1094071654,Liverpool r.no.565 Serp_job,97,,,
735,2090,OSTER,Oster reversible blade 6 blades,1115561690,Liverpool r.no.565 Serp_job,97,,,

In [101]:
file='brand_mapping_liverpool {}.xlsx'.format(serp_details['job_name'][0])
file
final_df.to_excel(file)

'brand_mapping_liverpool Liverpool r.no.565 Serp_job .xlsx'

In [ ]:
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders

email_user = 'alerts@1digitalstack.ai'
email_password = ''
email_send = ['ghansham.pindoriya@1digitalstack.ai','karan.kumar@1digitalstack.ai','sambhav.jain@1digitalstack.ai','arihant.singh@1digitalstack.ai','kinshu@1digitalstack.ai','ankur.dwivedi@1digitalstack.ai']

subject = file
msg = MIMEMultipart()
msg['From'] = email_user
#msg['From'] = "'Abhishek' <{email_user}>"
msg['To'] = ', '.join(email_send)
msg['Subject'] = subject

body = 'Hi,\n\nPFA of today''s brand mapping of amazon. Please check brand mapping for following jobs.\n{}'.format(jobs_name)
msg.attach(MIMEText(body,'plain'))

filename=[file]

for file in filename:
    attachment  =open(file,'rb')
    part = MIMEBase('application','octet-stream')
    part.set_payload((attachment).read())
    encoders.encode_base64(part)
    part.add_header('Content-Disposition',"attachment; filename= "+file)
    msg.attach(part)
    text = msg.as_string()

server = smtplib.SMTP('1digitalstack.com',25)
#server.login(email_user,email_password)

server.sendmail(email_user,email_send,text)
server.quit()